name: Deploy Static Website to Azure

on: 
  push:
    branches:
      - main
    paths:
      - 'website/**'  # Trigger only when files in 'website/' change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to Azure Blob Storage
        uses: azure/CLI@v2
        with:
          azcliversion: 2.59.0  # optional
          inlineScript: |
            az storage blob upload-batch \
              --account-name "$AZURE_STORAGE_ACCOUNT" \
              --account-key "$AZURE_STORAGE_KEY" \
              --destination "\$web" \
              --source "./website" \
              --overwrite
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
