name: Deploy Static Website to Azure

on: [push]
  
    branches:
      - main
    paths:
      - 'website/**'  # Trigger only if files in 'site/' change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Azure CLI
      uses: azure/CLI@v2

    - name: Run deployment script
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      run: |
        az storage blob upload-batch \
          --account-name "$AZURE_STORAGE_ACCOUNT" \
          --account-key "$AZURE_STORAGE_KEY" \
          --destination "\$web" \
          --source "./website" \
          --overwrite
          
# File: .github/workflows/workflow.yml


